# -*- coding: utf-8 -*-
"""
/***************************************************************************
 EarthObservationPavementAnalysis
                                 A QGIS plugin
 This plugin prepares the data sets to train, validate and assess earth observation imagery for pavement analysis
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-05-01
        copyright            : (C) 2024 by TRL Software
        email                : ckettell@trl.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load EarthObservationPavementAnalysis class from file EarthObservationPavementAnalysis.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .EO_pavement_analysis import EarthObservationPavementAnalysis
    return EarthObservationPavementAnalysis(iface)
